### ISSUE TITLE
optionally switch the trigger command to "Tango, "

### ISSUE THREAD

**Issue by mcarmody** [mcarmody/ArbiterBot#10]
The bot on Purge's server is posing as his dog, which is named Tango.  This is trivial to switch but I want to make it a command to switch if possible, so that we can do it after Purge has a separate instance of the bot running.

**Comment by timzwiebel** [comment]
Does `!help set serverprefix` not meet your needs? It allows per-server prefixes. Something like `!set serverprefix ! "Tango, "` should set it to either `!` or `Tango, ` (there's a space at the end there). And then only that server will use "Tango, ".

**Comment by timzwiebel** [comment]
BTW, you can also have per-server admin roles and mod roles, which might solve our permission checking needs better than a global whitelist. I'm not sure what an "admin" or "mod" does, or what the difference is, but I assume there's a check somewhere that I can apply to the commands we want to protect (e.g., the dota ones like heropoll).

**Comment by timzwiebel** [comment]
Seems like this is addressed by `set serverprefix`. Closing.
