### ISSUE TITLE
add random selection of X users from channel

### ISSUE THREAD

**Issue by mcarmody** [mcarmody/ArbiterBot#3]

**Comment by timzwiebel** [comment]
IIUC, this is to select people to play in a party when there are more players than slots available.

How would this work? Assuming the command name is `selectusers` (can discuss the name later)...
`!selectusers 3` would look at everyone who is both in the text channel and also online and would randomly select 3 of them and print their names? Something like...
```
3 random users selected:
 - User1
 - User2
 - User3
```
Do we want to @ mention the users? Or PM them? Do they have to respond to confirm their participation?

**Comment by mcarmody** [comment]
I think something more like, "type 'Here' in the next 30 seconds to be included" and then those players get randomly selected from and @ messages.
