### ISSUE TITLE
Ensure that mention permissions aren't bypassed

### ISSUE THREAD

**Issue by timzwiebel** [mcarmody/ArbiterBot#4]
Ensure that users can't use heropoll commands that have mentions like @everyone in them to circumvent mention permissions (since the bot might have permission to use mentions while the user does not).

**Comment by mcarmody** [comment]
what happens if the bot doesn't have @everyone mention permissions and types out @everyone (nothing, IIRC)? Could this be brute-forced resolved by restricting bot permissions?

**Comment by timzwiebel** [comment]
Yes. It's the basic rule of sanitizing user input when using user-created content. The names of the heroes can be anything right now (e.g., `!heropoll a mid hero, an offlaner`). So even if I don't have permission to use @everyone, I could do something like `!heropoll @everyone check out my spam` and since the bot is the one saying it, it will work. But as you pointed out, it only works if the bot has permission to use @everyone. A more robust bot would check for mentions in the list of heroes, but if we just make sure the bot doesn't have permission in the few places it's running, that works too for now. I just figured I'd file a bug so we don't forget that this is a limitation.
