### ISSUE TITLE
Document the "Manage Messages" permission

### ISSUE THREAD

**Issue by timzwiebel** [mcarmody/ArbiterBot#5]
The bot needs the "Manage Messages" permission to delete vote messages after counting them so they don't clutter up the channel. This should be documented (in the help).

**Comment by mcarmody** [comment]
Agreed, and probably it should also throw out a message if it doesn't have that whenever it's pinged for help or info or something similar.

**Comment by timzwiebel** [comment]
Fixed in d840fcc.
