### ISSUE TITLE
Poll authors can block future polls in a channel

### ISSUE THREAD

**Issue by timzwiebel** [mcarmody/ArbiterBot#7]
As it is currently written, only 1 poll can be running at a time within any given text channel. Furthermore, only the author of the poll can stop that poll. As such, if someone starts a poll and never stops it, no one else can run a poll in that channel until either the author stops the poll or the bot is restarted (polls live in RAM).

There are a few options to fix this:
 - allow any admin to stop the poll (probably the easiest solution)
 - the poll can have a timeout

**Comment by mcarmody** [comment]
Definitely both options.
